FROM golang:1.24 AS builder
WORKDIR /app
ENV CGO_ENABLED=0 GOOS=linux GOFLAGS=-p=1
COPY go.mod go.sum ./
RUN go mod download
COPY . .
# ...
RUN go build -trimpath -ldflags="-s -w" -o /scheduler ./cmd/scheduler/main.go

FROM gcr.io/distroless/base-debian12
COPY --from=builder /scheduler /scheduler
ENTRYPOINT ["/scheduler"]
