FROM golang:1.24 AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o /scheduler ./cmd/scheduler/main.go

FROM gcr.io/distroless/base-debian12
COPY --from=builder /scheduler /scheduler
ENTRYPOINT ["/scheduler"]
