FROM golang:1.24 AS builder
ARG svc
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o /${svc} ./cmd/${svc}/main.go

FROM gcr.io/distroless/base-debian12
ARG svc
COPY --from=builder /${svc} /${svc}
ENTRYPOINT ["/${svc}"]
