FROM golang:1.24 AS builder
ARG svc
ARG bin="${svc}"
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN test -n "${svc}" \
    && CGO_ENABLED=0 GOOS=linux go build -o "/${bin}" "./cmd/${svc}/main.go"

FROM gcr.io/distroless/base-debian12
ARG bin
COPY --from=builder "/${bin}" "/${bin}"
ENTRYPOINT ["/${bin}"]
